[package]
name = "directed"
version = "0.1.1"
edition = "2024"
description = "Evaluate programs based on Directed Acrylic Graphs"
license = "MIT"

[dependencies]
directed-stage-macro = { version = "0.1.1", path = "../directed-stage-macro" }
anyhow = "1.0.98"
daggy = "0.9.0"
slab = "0.4.9"
