[package]
name = "directed"
version = "0.4.0"
edition = "2024"
description = "Evaluate programs based on Directed Acrylic Graphs"
license = "MIT"

[dependencies]
directed-stage-macro = { version = "0.4.0", path = "../directed-stage-macro" }
futures = { version = "0.3", default-features = false, features = ["std"] }
slab = "0.4"
thiserror = "2.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"], optional = true }

[features]
default = []
tokio = ["dep:tokio"]

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
