[package]
name = "directed"
version = "0.1.0"
edition = "2024"

[dependencies]
directed-stage-macro = { version = "0.1.0", path = "../directed-stage-macro" }
anyhow = "1.0.98"
daggy = "0.9.0"
slab = "0.4.9"
